# Site settings
title:          T_PAGEFLT
description:    "Personal blog about low-level programming, security, and open-source software."
url:            "https://t.pagef.lt"

# Author
author:
  name:         Dimitris Karagkasidis
  url:          https://t.pagef.lt
  email:        t.pagef.lt@gmail.com
  twitter:      https://twitter.com/t_pageflt
  github:       https://github.com/pageflt
  mastodon:     https://infosec.exchange/web/@t_pageflt 

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Permalinks
permalink:      /:title
